name: Run Selenium UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Start server in background
        run: |
          node server.js &
          sleep 5

      - name: Run Selenium tests (headless)
        run: node test-selenium.js
